### ISSUE TITLE
TemperatureScaling().transform() binary-case output

### ISSUE THREAD

**Issue by Abdul-Moeed** [EFS-OpenSource/calibration-framework#10]
`TemperatureScaling().transform()` returns confidences for the second class in the binary classification case. This behavior seems unintuitive; ideally return shape should be `(n, k)`, but if it has to be `(n,)` then it should return confidences of the first class rather than the second.

**Comment by fabiankueppers** [comment]
Agree. Best prectice should be to return same shape as input array. Noticed for next release

**Comment by dsvrsec** [comment]
Is this issue fixed, because I am receiving the array with 1 dimension after transform,instead of 2 dimension incase of two label classification problem

**Comment by fabiankueppers** [comment]
This is notified for the next release but not fixed atm

**Comment by fabiankueppers** [comment]
Due to missing interest, this feature will be discarded for the moment. Re-open if necessary.
