### ISSUE TITLE
DType Error for LogisticCalibrationDependent

### ISSUE THREAD

**Issue by mlw214** [EFS-OpenSource/calibration-framework#31]
I recently upgraded from netcal version 1.2.1 to 1.3.1, and now I can no longer fit a `LogisticCalibrationDependent` instance without the following error occurring: `RuntimeError: Found dtype Double but expected Float`. My code matches the examples in terms of dtypes for the features (`np.float32`) and matched vector (`np.int32`). Exact same code works with version 1.2.1.

The error is being thrown from the following line in `AbstractLogisticRegression` (line 582 according to pdb):
```py
torch.nn.BCELoss(reduction='mean')(torch.sigmoid(x), y)
```

I'm using PyTorch version 1.11.0.

**Comment by fabiankueppers** [comment]
Thanks for pointing out, will fix this asap.

**Comment by fabiankueppers** [comment]
Fixed with the latest pull request. Please check and reopen if this issue has not been resolved so far.
