### ISSUE TITLE
mean_estimate flag in scaling calibration transform method does not work as intended

### ISSUE THREAD

**Issue by 21xiangyi** [EFS-OpenSource/calibration-framework#42]
When the `mean_estimate` parameter is flagged as True, it returns the error `expected np.ndarray (got Tensor)`. This only happens when method in the constructor is initialized as 'variational' or 'mcmc'. When method is initialized as 'mle', there are no problems yielding numpy array, i.e. inputs to the fit and transform are valid.

**Comment by fabiankueppers** [comment]
Hi, can you please give the full stack trace of the error? Thanks!

**Comment by fabiankueppers** [comment]
Closing this issue for now due to missing information. Please re-open if necessary.
