### ISSUE TITLE
How to evaluate using D-ECE

### ISSUE THREAD

**Issue by nisargshah1999** [EFS-OpenSource/calibration-framework#46]
Hi I am trying to evaluate my object detection model
Should I concat predictions for all images together, or how to do it
Is there code with working example?
Thanks

**Comment by fabiankueppers** [comment]
Hi @nisargshah1999, yes for object detection evaluation, you simply concat all detections into a single tensor of shape (N, [x, y, ...]) where N is the number of individual objects and x, y are the respective (optional) bounding box information you can additionally pass to the function call. Also remember to provide the respective matching flag as ground-truth (1 stands for a predicted object matching a ground-truth one, 0 represents a false positive) within a single tensor of shape (N,).

Hope this helps. Please close the issue if so.
Best regards

**Comment by nisargshah1999** [comment]
Thanks @fabiankueppers for your reply, and also making a well documented repo; it is indeed useful
I have one more question, wouldn't it be more useful, if class level information is used for D-ECE
Like , 0 for False positive and    1,..,n_classes for correct predicted object, relative to specific class?

**Comment by fabiankueppers** [comment]
This is a very interesting approach, I will definetly take this into account for future releases, thank you very much!
