### ISSUE TITLE
RuntimeError: On detection mode, it is mandatory to provide binary labels y in [0,1].

### ISSUE THREAD

**Issue by rishabh706** [EFS-OpenSource/calibration-framework#49]
Hi,
I am passing the below input to the LogisticCalibration, but it is giving the runtime error.

`confidence_scores = np.array([0.70745564, 0.71694]
  matched = np.array([1, 1] # as both are boxes are matched with the ground truth's
  relative_x_position = np.array([0.7543349742889405, 0.24766819924116135])
  input = np.stack((confidences_scores, relative_x_position), axis=1)

  lr = LogisticCalibration(detection=True, use_cuda=False)    # flag 'detection=True' is mandatory for this method
  lr.fit(input, matched)
  calibrated = lr.transform(input)
`
<img width="1347" alt="Screenshot 2023-11-02 at 4 24 55 PM" src="https://github.com/EFS-OpenSource/calibration-framework/assets/37527532/02379c1c-cfdc-4268-ae24-524a1ab109d9">

Thanks

**Comment by fabiankueppers** [comment]
Thanks for pointing out, I will fix this asap.
