### ISSUE TITLE
NaN outputs

### ISSUE THREAD

**Issue by Ruhallah93** [EFS-OpenSource/calibration-framework#56]
Sometimes I get NaN with the transform function.
In these cases, the below warning is observed when calling fit function:
/usr/local/lib/python3.10/dist-packages/netcal/binning/HistogramBinning.py:280: RuntimeWarning: invalid value encountered in divide
  calibrated = np.divide(calibrated, normalizer)

**Comment by fabiankueppers** [comment]
Hi @Ruhallah93, sorry for the delayed response.
Looks like the normalizer is getting 0. This might only be the case when netcal detects multi-class classification but no label. This looks a little bit odd to me. Do you have any code snippets to reproduce?

**Comment by fabiankueppers** [comment]
Closing this issue for now until new information are available. Please re-open if necessary.
