### ISSUE TITLE
ENIR

### ISSUE THREAD

**Issue by Ruhallah93** [EFS-OpenSource/calibration-framework#57]
The following error sometimes occurs when working with ENIR

ValueError: Array of size zero to minimum decrement operation that has no identity

**Comment by Ruhallah93** [comment]
I would be grateful if you could explain the reason for this error. I am in an urgent situation.

**Comment by fabiankueppers** [comment]
Hi @Ruhallah93,
without any further information, it is nearly impossible to help you. Which netcal version? Which python version? Could you give at least the full stack trace? Also, some information about the used data would also be very helpful to reproduce this error. Thank you.

**Comment by fabiankueppers** [comment]
As long as no further information is provided, I will close this issue for now. Please re-open if necessary.
